package rewrite.accessible

import zio._
import zio.managed._
import zio.stream._


object AllCapabilities {
  trait Service {
    val static: UIO[String]
    def zeroArgs: UIO[Int]
    def zeroArgsWithParens(): UIO[Long]
    def singleArg(arg1: Int): UIO[String]
    def multiArgs(arg1: Int, arg2: Long): UIO[String]
    def multiParamLists(arg1: Int)(arg2: Long): UIO[String]
    def typedVarargs[T](arg1: Int, arg2: T*): UIO[T]
    def command(arg1: Int): UIO[Unit]
    def overloaded(arg1: Int): UIO[String]
    def overloaded(arg1: Long): UIO[String]

    val staticManaged: UManaged[String]
    def zeroArgsManaged: UManaged[Int]
    def zeroArgsTypedManaged[T]: UManaged[T]
    def zeroArgsWithParensManaged(): UManaged[Long]
    def singleArgManaged(arg1: Int): UManaged[String]
    def multiArgsManaged(arg1: Int, arg2: Long): UManaged[String]
    def multiParamListsManaged(arg1: Int)(arg2: Long): UManaged[String]
    def typedVarargsManaged[T](arg1: Int, arg2: T*): UManaged[T]
    def commandManaged(arg1: Int): UManaged[Unit]
    def overloadedManaged(arg1: Int): UManaged[String]
    def overloadedManaged(arg1: Long): UManaged[String]

    def function(arg1: Int): String
    def sink(arg1: Int): ZSink[Any, Nothing, Int, Int, List[Int]]
    def stream(arg1: Int): ZStream[Any, Nothing, Int]
  }

  // format: off
  // Generated by ZIO Accessible CodeGen Scalafix Rule
  val static: ZIO[AllCapabilities.Service, Nothing, String] = ZIO.serviceWithZIO[Service](_.static)
  def zeroArgs(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, Int] = ZIO.serviceWithZIO[Service](_.zeroArgs)
  def zeroArgsWithParens()(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, Long] = ZIO.serviceWithZIO[Service](_.zeroArgsWithParens())
  def singleArg(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, String] = ZIO.serviceWithZIO[Service](_.singleArg(arg1))
  def multiArgs(arg1: Int, arg2: Long)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, String] = ZIO.serviceWithZIO[Service](_.multiArgs(arg1, arg2))
  def multiParamLists(arg1: Int)(arg2: Long)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, String] = ZIO.serviceWithZIO[Service](_.multiParamLists(arg1)(arg2))
  def typedVarargs[T](arg1: Int, arg2: T*)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, T] = ZIO.serviceWithZIO[Service](_.typedVarargs[T](arg1, arg2: _*))
  def command(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, Unit] = ZIO.serviceWithZIO[Service](_.command(arg1))
  def overloaded(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, String] = ZIO.serviceWithZIO[Service](_.overloaded(arg1))
  def overloaded(arg1: Long)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, String] = ZIO.serviceWithZIO[Service](_.overloaded(arg1))
  val staticManaged: ZManaged[AllCapabilities.Service, Nothing, String] = ZManaged.serviceWithManaged[Service](_.staticManaged)
  def zeroArgsManaged(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, Int] = ZManaged.serviceWithManaged[Service](_.zeroArgsManaged)
  def zeroArgsTypedManaged[T](using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, T] = ZManaged.serviceWithManaged[Service](_.zeroArgsTypedManaged[T])
  def zeroArgsWithParensManaged()(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, Long] = ZManaged.serviceWithManaged[Service](_.zeroArgsWithParensManaged())
  def singleArgManaged(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, String] = ZManaged.serviceWithManaged[Service](_.singleArgManaged(arg1))
  def multiArgsManaged(arg1: Int, arg2: Long)(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, String] = ZManaged.serviceWithManaged[Service](_.multiArgsManaged(arg1, arg2))
  def multiParamListsManaged(arg1: Int)(arg2: Long)(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, String] = ZManaged.serviceWithManaged[Service](_.multiParamListsManaged(arg1)(arg2))
  def typedVarargsManaged[T](arg1: Int, arg2: T*)(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, T] = ZManaged.serviceWithManaged[Service](_.typedVarargsManaged[T](arg1, arg2: _*))
  def commandManaged(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, Unit] = ZManaged.serviceWithManaged[Service](_.commandManaged(arg1))
  def overloadedManaged(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, String] = ZManaged.serviceWithManaged[Service](_.overloadedManaged(arg1))
  def overloadedManaged(arg1: Long)(using izumi.reflect.Tag[AllCapabilities.Service]): ZManaged[AllCapabilities.Service, Nothing, String] = ZManaged.serviceWithManaged[Service](_.overloadedManaged(arg1))
  def function(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZIO[AllCapabilities.Service, Nothing, String] = ZIO.serviceWith[Service](_.function(arg1))
  def sink(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZSink[AllCapabilities.Service, Nothing, Int, Int, List[Int]] = ZSink.environmentWithSink[Service][AllCapabilities.Service & Any, Nothing, Int, Int, List[Int]](_.get[AllCapabilities.Service].sink(arg1))
  def stream(arg1: Int)(using izumi.reflect.Tag[AllCapabilities.Service]): ZStream[AllCapabilities.Service, Nothing, Int] = ZStream.serviceWithStream[Service](_.stream(arg1))
  // format: on
}

object AllCapabilitiesTest {
  val static: ZIO[AllCapabilities.Service, Nothing, String] = AllCapabilities.static
  def zeroArgs: ZIO[AllCapabilities.Service, Nothing, Int] = AllCapabilities.zeroArgs
  def zeroArgsWithParens(): ZIO[AllCapabilities.Service, Nothing, Long] = AllCapabilities.zeroArgsWithParens()
  def singleArg(arg1: Int): ZIO[AllCapabilities.Service, Nothing, String] = AllCapabilities.singleArg(arg1)
  def multiArgs(arg1: Int, arg2: Long): ZIO[AllCapabilities.Service, Nothing, String] =
    AllCapabilities.multiArgs(arg1, arg2)
  def multiParamLists(arg1: Int)(arg2: Long): ZIO[AllCapabilities.Service, Nothing, String] =
    AllCapabilities.multiParamLists(arg1)(arg2)
  def typedVarargs[T](arg1: Int, arg2: T*): ZIO[AllCapabilities.Service, Nothing, T] =
    AllCapabilities.typedVarargs[T](arg1, arg2: _*)
  def command(arg1: Int): ZIO[AllCapabilities.Service, Nothing, Unit] = AllCapabilities.command(arg1)
  def overloaded(arg1: Int): ZIO[AllCapabilities.Service, Nothing, String] = AllCapabilities.overloaded(arg1)
  def overloaded(arg1: Long): ZIO[AllCapabilities.Service, Nothing, String] = AllCapabilities.overloaded(arg1)

  val staticManaged: ZManaged[AllCapabilities.Service, Nothing, String] = AllCapabilities.staticManaged
  def zeroArgsManaged: ZManaged[AllCapabilities.Service, Nothing, Int] = AllCapabilities.zeroArgsManaged
  def zeroArgsTypedManaged[T]: ZManaged[AllCapabilities.Service, Nothing, T] = AllCapabilities.zeroArgsTypedManaged[T]
  def zeroArgsWithParensManaged(): ZManaged[AllCapabilities.Service, Nothing, Long] =
    AllCapabilities.zeroArgsWithParensManaged()
  def singleArgManaged(arg1: Int): ZManaged[AllCapabilities.Service, Nothing, String] =
    AllCapabilities.singleArgManaged(arg1)
  def multiArgsManaged(arg1: Int, arg2: Long): ZManaged[AllCapabilities.Service, Nothing, String] =
    AllCapabilities.multiArgsManaged(arg1, arg2)
  def multiParamListsManaged(arg1: Int)(arg2: Long): ZManaged[AllCapabilities.Service, Nothing, String] =
    AllCapabilities.multiParamListsManaged(arg1)(arg2)
  def typedVarargsManaged[T](arg1: Int, arg2: T*): ZManaged[AllCapabilities.Service, Nothing, T] =
    AllCapabilities.typedVarargsManaged[T](arg1, arg2: _*)
  def commandManaged(arg1: Int): ZManaged[AllCapabilities.Service, Nothing, Unit] = AllCapabilities.commandManaged(arg1)
  def overloadedManaged(arg1: Int): ZManaged[AllCapabilities.Service, Nothing, String] =
    AllCapabilities.overloadedManaged(arg1)
  def overloadedManaged(arg1: Long): ZManaged[AllCapabilities.Service, Nothing, String] =
    AllCapabilities.overloadedManaged(arg1)

  def function(arg1: Int): ZIO[AllCapabilities.Service, Throwable, String] = AllCapabilities.function(arg1)
  def sink(arg1: Int): ZSink[AllCapabilities.Service, Nothing, Int, Int, List[Int]] = AllCapabilities.sink(arg1)
  def stream(arg1: Int): ZStream[AllCapabilities.Service, Nothing, Int] = AllCapabilities.stream(arg1)
}
